name: Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - main
    paths:
      - 'app/frontend/**'
      - 'app/backend/**'
  workflow_dispatch:

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies (frontend & backend)
        run: |
          cd app/frontend && npm ci
          cd ../backend && npm ci

      - name: Build frontend
        run: |
          cd app/frontend
          npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (auto)
          action: 'upload'
          app_location: 'app/frontend' # フロントエンドのパス
          api_location: 'app/backend'         # APIのパス
          output_location: 'build'            # Reactのビルド出力

  loadtest:
    runs-on: ubuntu-latest
    needs: build_and_deploy_job
    
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Run Azure Load Testing
        uses: azure/load-testing@v1.1.27
        with:
          loadtestConfigFile: loadtest/loadtest.yaml
          resourceGroup: rg-devops
          loadtestResource: LoadTest-demo
        env:
          TARGET_ENDPOINT=https://lively-bush-0895cf100.6.azurestaticapps.net/api/notes
      - name: アーティファクトとして結果を保存
        uses: actions/upload-artifact@v4
        with:
          name: loadtest-results
          path: .azureloadtestrun/**