name: Deploy backend api to Azure Functions

on:
  push:
    branches: [ main ]
    paths:
      - 'app/api/**'
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build, Test and Deploy Function
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd app/api
          npm ci

      - name: Run tests
        run: |
          cd app/api
          npm test --if-present

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.FUNCTION_APP_NAME }}
          package: './app/api'

      - name: Post-deploy smoke test
        run: |
          echo "Deployed to Function: ${{ secrets.FUNCTION_APP_NAME }}"
