name: Azure Load Test

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'loadtest/**'
      - '.github/workflows/loadtest.yml'

jobs:
  loadtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Run Azure Load Testing
        uses: azure/load-testing@v1.1.27
        with:
          loadtestConfigFile: loadtest/loadtest.yaml
          resourceGroup: rg-devops
          loadtestResource: LoadTest-demo
      - name: アーティファクトとして結果を保存
        uses: actions/upload-artifact@v4
        with:
          name: loadtest-results
          path: .azureloadtestrun/**
